#!/bin/bash -e

thisdir="$(cd "$(dirname "$0")"; pwd)"
source "$thisdir/python-versions.sh"

pip_options=""

if [[ -n "$TOX_BOOTSTRAP_QUIET" ]]; then
    pip_options="--quiet"
    function run()
    {
        "$@"
    }
else
    function run()
    {
        echo "$@"
        "$@"
    }
fi


run mkdir -p .tox
run "$PYTHON" -m venv .tox/bootstrap
run source .tox/bootstrap/bin/activate
run pip $pip_options install $pip_options --upgrade pip
run pip $pip_options install $pip_options "tox~=$TOX_VERSION"
run exec tox "$@"
